[global]
   workgroup = WORKGROUP
   server string = Rackflow ISO library
   security = user
   map to guest = never
   load printers = no
   printing = bsd
   disable spoolss = yes
   dns proxy = no
   passdb backend = tdbsam
   smb ports = 445
   min protocol = SMB2
   server min protocol = SMB2

[isos]
   path = /data/isos
   browseable = yes
   read only = yes
   guest ok = no
   writable = no
   force user = root
